export type MuaphungSinh = {
    week1: Date,
    week2: Date,
    week3: Date,
    week4: Date
}
export type simpleDate  = {
    year: number,
    month: number,
    day: number
};
export type NamPhungVu = {
    year: number,
    yearABC: string,
    oddEven: string,
    leDucMeChuaTroi: Date,
    dangchuaGiesuTrongDenThanh: Date
    theEpiphanyOfTheLord: Date,
    leChuaChiuPhepRua: Date,
    ashWed: Date,
    firstSundayOfLent: Date,
    secondSundayOfLent: Date,
    thirdSundayOfLent: Date,
    fourthSundayOfLent: Date,
    fifthSundayOfLent: Date,
    palmSunday: Date,
    easterSunday: Date,
    secondSundayOfEaster: Date,
    thirdSundayOfEaster: Date,
    fourthSundayOfEaster: Date,
    fifthSundayOfEaster: Date,
    sixthSundayOfEaster: Date,
    theAscentionOfTheLord: Date,
    pentecostSunday: Date,
    leChuaBaNgoi: Date,
    leMinhMauThanhChua: Date,
    leThanhTamChuaGieSu: Date,
    chuaKitoVua: Date,
    firstSundayOfAdvent: Date,
    secondSundayOfAdvent: Date,
    thirdSundayOfAdvent: Date,
    fourthSundayOfAdvent: Date,
    christmas: Date,
    leThanhGia: Date,
    firstOrdinarySundayAfterPentecostSunday: number, // chua nhat dau tien sau le chua thanh than hien xuong la chua nhat thuong nien thu may ?
}
export const nameOfDays = {
    year: 'year( Năm)',
    yearABC: 'A|B|C (năm A|B|C)',
    oddEven: 'Odd|Even (Năm chẵn lẻ)',
    theEpiphanyOfTheLord: 'The Epiphany of the Lord (Lễ Chúa Hiển Linh)',
    leChuaChiuPhepRua: 'Lễ Chúa chịu phép rửa',
    ashWed: 'Ash Wednesday (Thứ tư lễ tro)',
    firstSundayOfLent: 'First Sunday of Lent (Chúa nhật thứ nhất mùa chay)',
    secondSundayOfLent: 'Second Sunday of Lent (Chúa nhật thứ 2 mùa chay)',
    thirdSundayOfLent: 'Third Sunday of Lent (Chúa nhật thứ 3 mùa chay)',
    fourthSundayOfLent: 'Fourth Sunday of Lent (Chúa nhật thứ 4 mùa chay)',
    fifthSundayOfLent: 'Fifth Sunday of Lent (Chúa nhật thứ 5 mùa chay)',
    palmSunday: 'Palm Sunday (Lễ Lá)',
    easterSunday: 'Easter Sunda (Phục sinh)',
    secondSundayOfEaster: 'Second Sunday of Easter (Chúa nhật thứ 2 phục sinh)',
    thirdSundayOfEaster: 'Third Sunday of Easter (Chúa nhật thứ 3 phục sinh)',
    fourthSundayOfEaster: 'Fourth Sunday of Easter (Chúa nhật thứ 4 phục sinh)',
    fifthSundayOfEaster: 'Fifth Sunday of Easter (Chúa nhật thứ 5 phục sinh)',
    sixthSundayOfEaster: 'Sixth Sunday of Easter (Chúa nhật thứ 6 phục sinh)',
    theAscentionOfTheLord: 'The Ascention of the Lord (Lễ Chúa Lên Trời)',
    pentecostSunday: 'Pentecost Sunday (Lễ Chúa Thánh Thần hiện xuống)',
    firstSundayOfAdvent: 'First Sunday of Advent (Chúa nhật thứ nhất mùa vọng)',
    secondSundayOfAdvent: 'Second Sunday of Advent (Chúa nhật thứ 2 mùa vọng)',
    thirdSundayOfAdvent: 'Third Sunday of Advent (Chúa nhật thứ 3 mùa vọng)',
    fourthSundayOfAdvent: 'Fourth Sunday of Advent (Chúa nhật thứ tư mùa vọng)',
    christmas: 'Christmas (Giáng sinh)',
    leThanhGia: 'Lễ Thánh Gia',
    chuaKitoVua: 'Lễ Chúa KiTo Vua',
    firstOrdinarySundayAfterPentecostSunday: 'Chua Nhat Thuong Nien sau Le Chua Thanh than hien xuong',
    leDucMeChuaTroi: 'Thánh Ma-ri-a, Ðức Mẹ Chúa Trời',
    dangchuaGiesuTrongDenThanh: 'Dâng Chúa Giê-su Trong Đền Thánh',
    leChuaBaNgoi: 'Lễ Chúa Ba Ngôi',
    leMinhMauThanhChua: 'Lễ Mình Máu Thánh Chúa',
    leThanhTamChuaGieSu: 'Lễ Thánh Tâm Chúa Giê Su',
};
  